# Generated by Django 3.2.6 on 2021-08-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat_description', models.CharField(max_length=100)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('Date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
